/*

 BGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\oldgbdk\TileDesigner\map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bgmapWidth 32
#define bgmapHeight 32
#define bgmapBank 0

extern unsigned char bgmap[];

/* End of BGMAP.H */
